version: "3"

services:
  client:
    container_name: client
    build: 
      context: ./client
      dockerfile: ./Dockerfile.development
    volumes:
      - "./client:/app"
      - "/app/node_modules"
    ports:
      - "3000:3000"
    
  server:
    container_name: server
    build: 
      context: ./server
      dockerfile: ./Dockerfile.development
    env_file: ./server/.env.development.local
    volumes:
      - "./server:/app"
      - "/app/node_modules"
    ports:
      - "4000:4000"

  database:
    container_name: database
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=rental_calculator
    volumes:
      - ./database/sql:/docker-entrypoint-initdb.d
      - ./database/postgresql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
